services:
  code:
    build:
      context: .
    container_name: quantumSecure-backend-code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
